CREATE TABLE IF NOT EXISTS `ai_invocation_trace` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `trace_id` varchar(64) NOT NULL COMMENT 'Trace id',
  `session_id` varchar(128) DEFAULT NULL COMMENT 'Session id',
  `user_id` bigint DEFAULT NULL COMMENT 'User id',
  `agent_id` varchar(128) DEFAULT NULL COMMENT 'Agent id',
  `agent_name` varchar(128) DEFAULT NULL COMMENT 'Agent name',
  `scene_code` varchar(64) DEFAULT NULL COMMENT 'Business scene',
  `stage` varchar(64) DEFAULT NULL COMMENT 'Invocation stage',
  `provider` varchar(64) DEFAULT NULL COMMENT 'spring-ai/langchain4j/xunfei',
  `model_or_flow_id` varchar(128) DEFAULT NULL COMMENT 'Model or flow id',
  `event_type` varchar(16) NOT NULL COMMENT 'START/END/ERROR',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration_ms` bigint DEFAULT NULL,
  `input_summary` text,
  `output_summary` text,
  `error_message` text,
  `error_stack_trace` mediumtext,
  `request_key` varchar(256) DEFAULT NULL,
  `stream` tinyint DEFAULT 0,
  `metadata_json` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trace_id` (`trace_id`),
  KEY `idx_session_scene` (`session_id`, `scene_code`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Unified AI invocation traces';

CREATE TABLE IF NOT EXISTS `ai_tool_execution` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `trace_id` varchar(64) NOT NULL COMMENT 'Trace id',
  `session_id` varchar(128) DEFAULT NULL COMMENT 'Session id',
  `agent_id` varchar(128) DEFAULT NULL COMMENT 'Agent id',
  `scene_code` varchar(64) DEFAULT NULL COMMENT 'Business scene',
  `tool_name` varchar(128) NOT NULL COMMENT 'Tool name',
  `tool_input` text,
  `tool_output` text,
  `success` tinyint DEFAULT 1,
  `execution_time_ms` bigint DEFAULT NULL,
  `invocation_order` int DEFAULT 0,
  `error_message` text,
  `event_time` datetime DEFAULT NULL,
  `metadata_json` text,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_trace_id` (`trace_id`),
  KEY `idx_session_scene` (`session_id`, `scene_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Unified AI tool execution traces';

CREATE TABLE IF NOT EXISTS `ai_agent_session_stats` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `session_id` varchar(128) NOT NULL COMMENT 'Session id',
  `scene_code` varchar(64) NOT NULL COMMENT 'Business scene',
  `success_count` bigint DEFAULT 0,
  `failure_count` bigint DEFAULT 0,
  `total_duration_ms` bigint DEFAULT 0,
  `last_trace_id` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_scene` (`session_id`, `scene_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI agent session aggregate stats';
